### ISSUE TITLE
React 오타, RESTAPI & GraphQL

### ISSUE THREAD

**Issue by gmlwo530** [chiyodad/options4service#5]
안녕하세요.

Reactjs 오타인거 같아요!!

그리고 Rest와 GraphQL도 추가하는 것은어떻게 생각하시나요?

**Comment by chiyodad** [comment]
앗 제보 감사합니다 ㅎㅎ
네 GraphQL 도 점점 많이 쓰고 있는 것 같아 추가하도록 하겠습니다.

**Comment by gmlwo530** [comment]
네 감사합니다
